version: "3.9"
volumes:
  dbstore:

services:
  postgres:
    image: postgres:15.3
    volumes:
      - dbstore:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=root
